# Generated by Django 4.1.5 on 2023-01-27 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social_django.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_django', '0010_uid_db_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.AlterModelOptions(
            name='nonce',
            options={'verbose_name': 'Nonce', 'verbose_name_plural': 'Nonces'},
        ),
        migrations.AlterModelOptions(
            name='usersocialauth',
            options={'verbose_name': 'User social auth', 'verbose_name_plural': 'User social auths'},
        ),
        migrations.AlterField(
            model_name='association',
            name='assoc_type',
            field=models.CharField(max_length=64, verbose_name='Assoc type'),
        ),
        migrations.AlterField(
            model_name='association',
            name='handle',
            field=models.CharField(max_length=255, verbose_name='Handle'),
        ),
        migrations.AlterField(
            model_name='association',
            name='issued',
            field=models.IntegerField(verbose_name='Issued'),
        ),
        migrations.AlterField(
            model_name='association',
            name='lifetime',
            field=models.IntegerField(verbose_name='Lifetime'),
        ),
        migrations.AlterField(
            model_name='association',
            name='secret',
            field=models.CharField(max_length=255, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='association',
            name='server_url',
            field=models.CharField(max_length=255, verbose_name='Server url'),
        ),
        migrations.AlterField(
            model_name='nonce',
            name='salt',
            field=models.CharField(max_length=65, verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='nonce',
            name='server_url',
            field=models.CharField(max_length=255, verbose_name='Server url'),
        ),
        migrations.AlterField(
            model_name='nonce',
            name='timestamp',
            field=models.IntegerField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='extra_data',
            field=social_django.fields.JSONField(default=dict, verbose_name='Extra data'),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='provider',
            field=models.CharField(max_length=32, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='uid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auth', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
