# Generated by Django 4.1.5 on 2023-03-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=256, verbose_name='Verb')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Target id')),
                ('target_ct', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'post'), ('model', 'post')), models.Q(('app_label', 'account'), ('model', 'profile')), models.Q(('app_label', 'contact'), ('model', 'contact')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='contenttypes.contenttype', verbose_name='Target ct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ('-created',),
            },
        ),
    ]
